In [ ]:
import pandas as pd
import numpy as np

books = pd.DataFrame({
    'title': ['The Pragmatic Programmer', 'Clean Code', 'Python Crash Course',
              'Data Science from Scratch', 'Designing Data-Intensive Apps'],
    'author': ['Hunt & Thomas', 'Robert Martin', 'Eric Matthes',
               'Joel Grus', 'Martin Kleppmann'],
    'genre': ['Tech', 'Tech', 'Tech', 'Data', 'Data'],
    'price': [45.99, 38.50, 29.99, 42.00, 55.00],
    'units_sold': [120, 95, 200, 80, 60],
    'in_stock': [True, True, False, True, False]
})

## Challenge 1: Build and Inspect the Dataset

Tasks:

    Use .info() — how many non-null values does each column have?
    Use .describe() — what's the average price and maximum units sold?
    Add a revenue column: price × units_sold.
    What is the total revenue across all books?

In [237]:
print("Books DataFrame:")
display(books)

Books DataFrame:

,title,author,genre,price,units_sold,in_stock
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True
1,Clean Code,Robert Martin,Tech,38.50,95,True
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False

In [238]:
# how many non-null values in each column. 

non_null_counts = books.notnull().sum().to_frame().T.rename(index={0: 'non_null_count'})
# 'to_frame' displays the result as a table with column names and non-null counts
# 'T transposes the table to show column names as headers and non-null counts as a single row.
# 'rename' changes the index name from 0 to 'non_null_count' for better readability.

display(non_null_counts)

                title  author  genre  price  units_sold  in_stock
non_null_count      5       5      5      5           5         5

In [239]:
# what is the average price. what is maximum units sold.
display(books.describe())

average_price_of_books = books['price'].mean()
maximum_units_sold = books['units_sold'].max()
print(f"Average Price of Books: ${average_price_of_books:.2f}")
print(f"Maximum Units Sold: {maximum_units_sold}")

           price  units_sold
count   5.000000    5.000000
mean   42.296000  111.000000
std     9.232715   54.359912
min    29.990000   60.000000
25%    38.500000   80.000000
50%    42.000000   95.000000
75%    45.990000  120.000000
max    55.000000  200.000000

Average Price of Books: $42.30
Maximum Units Sold: 200

In [240]:
# revenue is price * units_sold and add it as a new column 'revenue'

books['revenue'] = books['price'] * books['units_sold']
print("Books DataFrame with 'revenue' column:")
display(books)

Books DataFrame with 'revenue' column:

,title,author,genre,price,units_sold,in_stock,revenue
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0

In [241]:
# total revenue for all the books

total_revenue = books['revenue'].sum()
print(f"Total Revenue for All Books: ${total_revenue:.2f}")

Total Revenue for All Books: $21834.30

## Challenge 2: Indexing & Filtering

Tasks:

    Use `.loc` to select only `title` and `revenue` for Data genre books.
    Use `.iloc` to retrieve the last 3 rows and first 3 columns.
    Filter books that are **in stock** AND have a **price above £40**.
    Find the book with the **highest revenue** using `.loc` with `.idxmax()`.

In [242]:
1.
# Use .loc to show only title and revenue for Data genre books.
print("Title and Revenue for Data Genre Books:")
display(books.loc[books['genre'] == 'Data', ['title', 'revenue']])


2.
# Use .iloc to retrieve the last 3 rows and first 3 columns.
print("Last 3 Rows and First 3 Columns:")
display(books.iloc[-3:, :3])


3.
# Filter books that are in stock AND have a price above £40.
filtered_books = books[(books['in_stock'] == True) & (books['price'] > 40)]
print("Books that are in stock AND have a price above £40:")
display(filtered_books)


4.
# Find the book with the highest revenue using .loc with .idxmax(). 
highest_revenue_book = books.loc[[books['revenue'].idxmax()]] 
# use double brackets [[...]] which return a DataFrame (not a Series), so it displays with the column names as headers and the data as a single row—exactly like the original books table format.
print("Book with the Highest Revenue:")
display(highest_revenue_book)

Title and Revenue for Data Genre Books:

                           title  revenue
3      Data Science from Scratch   3360.0
4  Designing Data-Intensive Apps   3300.0

Last 3 Rows and First 3 Columns:

                           title            author genre
2            Python Crash Course      Eric Matthes  Tech
3      Data Science from Scratch         Joel Grus  Data
4  Designing Data-Intensive Apps  Martin Kleppmann  Data

Books that are in stock AND have a price above £40:

,title,author,genre,price,units_sold,in_stock,revenue
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0

Book with the Highest Revenue:

,title,author,genre,price,units_sold,in_stock,revenue
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0

## Challenge 3: Transform, Sort & Rank

In [243]:
# 1.    Use .apply() to add a price_tier column: 'Budget' (< £35), 'Standard' (£35–£50), 'Premium' (> £50).
# define a function to categorize price
def categorize_price(price):
    return 'premium' if price > 50 else 'standard' if 35 <= price <= 50 else 'budget'

# apply the function to the 'price' column and create a new 'price_tier' column
books['price_tier'] = books['price'].apply(categorize_price)
print("Books DataFrame with 'price_tier' column:")
display(books)


# 2.    Sort the DataFrame by revenue descending.
# sort the books by revenue in descending order
sorted_books = books.sort_values(by='revenue', ascending=False)
print("Books sorted by revenue (descending):")
display(sorted_books)


# 3.    Add a sales_rank column using .rank(ascending=False).
# add a new column 'sales_rank' that ranks the books based on revenue, with 1 being the highest revenue.
books['sales_rank'] = books['revenue'].rank(ascending=False, method='min').astype(int)

# sort sales_rank in ascending order to show the highest revenue book at the top
print("Books with 'sales_rank' column, sorted by sales rank:")
display(books.sort_values(by='sales_rank')) 


# 4.    Use .map() to encode genre as a number: {'Tech': 0, 'Data': 1}.
# create a mapping dictionary for genre encoding
genre_mapping = {'Tech': 0, 'Data': 1}
books['genre'] = books['genre'].map(genre_mapping)
print("Books DataFrame with 'genre_encoded' column:")
display(books)

Books DataFrame with 'price_tier' column:

,title,author,genre,price,units_sold,in_stock,revenue,price_tier
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,standard
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,standard
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,budget
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,standard
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,premium

Books sorted by revenue (descending):

,title,author,genre,price,units_sold,in_stock,revenue,price_tier
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,budget
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,standard
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,standard
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,standard
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,premium

Books with 'sales_rank' column, sorted by sales rank:

,title,author,genre,price,units_sold,in_stock,revenue,price_tier,sales_rank
2,Python Crash Course,Eric Matthes,Tech,29.99,200,False,5998.0,budget,1
0,The Pragmatic Programmer,Hunt & Thomas,Tech,45.99,120,True,5518.8,standard,2
1,Clean Code,Robert Martin,Tech,38.50,95,True,3657.5,standard,3
3,Data Science from Scratch,Joel Grus,Data,42.00,80,True,3360.0,standard,4
4,Designing Data-Intensive Apps,Martin Kleppmann,Data,55.00,60,False,3300.0,premium,5

Books DataFrame with 'genre_encoded' column:

,title,author,genre,price,units_sold,in_stock,revenue,price_tier,sales_rank
0,The Pragmatic Programmer,Hunt & Thomas,0,45.99,120,True,5518.8,standard,2
1,Clean Code,Robert Martin,0,38.50,95,True,3657.5,standard,3
2,Python Crash Course,Eric Matthes,0,29.99,200,False,5998.0,budget,1
3,Data Science from Scratch,Joel Grus,1,42.00,80,True,3360.0,standard,4
4,Designing Data-Intensive Apps,Martin Kleppmann,1,55.00,60,False,3300.0,premium,5

## 🏆 Stretch Challenge (Optional)

The manager wants a report comparing average price and total revenue by price_tier. Use groupby() to generate this summary. Which tier contributes the most total revenue despite having the lowest average price?

In [244]:
summary = books.groupby('price_tier').agg(
    average_revenue=('revenue', 'mean'),
    total_revenue=('revenue', 'sum')
)
display(summary)

            average_revenue  total_revenue
price_tier
budget          5998.000000         5998.0
premium         3300.000000         3300.0
standard        4178.766667        12536.3