# Lesson 1.7: Introduction to Pandas

**Duration:** 3 Hours  
**Format:** Interactive Zoom Session

## 📋 Pre-Class Setup
Please run the cell below to ensure your environment is ready. We will use `numpy` and `pandas` throughout this lesson.

In [12]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("Numpy version:", np.__version__)

Pandas version: 2.1.4
Numpy version: 1.26.4

Concept 1: The Series

Definition: A Series is a one-dimensional labeled array.

Analogy: Think of a Series like a single column in an Excel sheet. It has values, and it has row labels (the index).

In [13]:
# A simple list of data
data = [10, 20, 30, 40]
# Converting it to a Pandas Series
s = pd.Series(data, index=['a', 'b', 'c', 'd'])
print(s)

a    10
b    20
c    30
d    40
dtype: int64

Concept 2: The DataFrame

Definition: A DataFrame is a 2-dimensional labeled data structure with columns of potentially different types.

Analogy: Think of a DataFrame like the whole Spreadsheet. It is essentially a collection of Series (columns) that share the same index (rows).

In [14]:
# A dictionary where keys are column names
data = {
    'Apples': [3, 2, 0, 1],
    'Oranges': [0, 3, 7, 2]
}
df = pd.DataFrame(data)
print(df)

   Apples  Oranges
0       3        0
1       2        3
2       0        7
3       1        2

---

## 🎯 Section 1: Creating & Modifying Data Structures (60 min)

### Learning Objectives (LO1)
By the end of this section, you will be able to:
- **Create** Series and DataFrames from raw data.
- **Modify** DataFrames by adding new columns and changing values.
- **Identify** the index and column components.
- **Detect** missing values using `isna()` and `notna()`.

### 📖 Concept: The Series
A Series is a one-dimensional array with labeled indices. It's the building block of a DataFrame.

In [15]:
# [DEMO] Creating a Series
obj = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [16]:
# if never specified, the index will be auto-generated as integers starting from 0
obj2 = pd.Series([4, 7, -5, 3])
obj2

0    4
1    7
2   -5
3    3
dtype: int64

In [17]:
# if the data contains mixed types, the Series will be of dtype 'object'
obj3 = pd.Series([4, 7, -5, 3,"text"])
obj3

0       4
1       7
2      -5
3       3
4    text
dtype: object

### 📖 Concept: The DataFrame
A DataFrame is a 2-dimensional labeled data structure. Think of it as a dictionary of Series objects (each column is a Series).

In [32]:
# [DEMO] Creating a DataFrame from a dictionary
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
# display the number of rows and columns in the DataFrame
frame.shape

(6, 3)

In [ ]:
#display the total number of elements in the DataFrame
frame.size

18

### 💡 Concept Demo: Inspecting & Modifying
1. `head()` and `tail()`
2. Accessing columns (dictionary syntax vs dot syntax)
3. Adding a new column

In [ ]:
# [DEMO] Inspecting data
print("First 5 rows:")
display(frame.head())

# [DEMO] Display the last 3 rows of the DataFrame
print("Last 3 rows:")
display(frame.tail(3))

# [DEMO] Accessing a column
print("Population column:")
display(frame['pop'])

# pop is a method that removes a column from the DataFrame and returns it as a Series
print("Do not use the same name as a column name to avoid confusion:")
frame.pop

First 5 rows:

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

Last 3 rows:

    state  year  pop
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

Population column:

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
5    3.2
Name: pop, dtype: float64

Do not use the same name as a column name to avoid confusion:

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
5    3.2
Name: pop, dtype: float64

In [33]:
# [DEMO] Adding a new column with a scalar value
frame['debt'] = 16.5
frame

    state  year  pop  debt
0    Ohio  2000  1.5  16.5
1    Ohio  2001  1.7  16.5
2    Ohio  2002  3.6  16.5
3  Nevada  2001  2.4  16.5
4  Nevada  2002  2.9  16.5
5  Nevada  2003  3.2  16.5

In [5]:
# [DEMO] Adding a calculated column
frame['eastern'] = frame.state == 'Ohio'
frame

    state  year  pop  debt  eastern
0    Ohio  2000  1.5  16.5     True
1    Ohio  2001  1.7  16.5     True
2    Ohio  2002  3.6  16.5     True
3  Nevada  2001  2.4  16.5    False
4  Nevada  2002  2.9  16.5    False
5  Nevada  2003  3.2  16.5    False

### 📖 Concept: Detecting Missing Data
Real-world data often has missing values (shown as `NaN`). Use `isna()` and `notna()` to detect them.

In [34]:
# [DEMO] Detecting missing values
data_with_nan = pd.Series([1, np.nan, 3.5, np.nan, 7])

print("Original data:")
display(data_with_nan)

print("\nWhich values are missing?")
display(data_with_nan.isna())

print("\nWhich values are NOT missing?")
display(data_with_nan.notna())

Original data:

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

Which values are missing?

0    False
1     True
2    False
3     True
4    False
dtype: bool

Which values are NOT missing?

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [37]:
print("Strings are considered as object dtype, and they do not have NaN values, so isna() will return False for all elements")
series_with_strings = pd.Series(['test', 'test2', 'test3', ])
print(series_with_strings.isna())

Strings are considered as object dtype, and they do not have NaN values, so isna() will return False for all elements
0    False
1    False
2    False
dtype: bool

### 🛠️ Activity: The Inventory System

**Scenario:** You manage a small grocery store. You need to track your fruit inventory.

**Tasks:**
1. Create a DataFrame named `inventory` from the provided dictionary `fruit_data`.
2. Add a new column `price` with values `[3.0, 4.0, 2.0, 5.0]`.
3. Add a column `total_value` which is `quantity * price`.
4. Create a boolean column `low_stock` that is `True` if quantity is less than 50.

In [ ]:
# [EXERCISE] Starter Code
fruit_data = {
    "fruit": ["Apple", "Banana", "Cherry", "Date"],
    "quantity": [100, 40, 200, 20]
}

# 1. Create DataFrame
inventory = pd.DataFrame(fruit_data)

# 2. Add Price
inventory['price'] = [1.2, 0.8, 2.5, 3.0]

# 3. Calculate Total_Value as new column
frame['total_value'] = inventory['quantity'] * inventory['price']

# 4. Flag Low Stock as True False based on quantity < 50
check = inventory['quantity'] < 50
inventory['low_stock'] = check

# Display result
inventory

    fruit  quantity  price  low_stock
0   Apple       100    1.2      False
1  Banana        40    0.8       True
2  Cherry       200    2.5      False
3    Date        20    3.0       True

---

## 🎯 Section 2: Indexing and Selection (60 min)

### Learning Objectives (LO2)
By the end of this section, you will be able to:
- **Differentiate** between label-based (`loc`) and position-based (`iloc`) indexing.
- **Apply** boolean filtering to select specific rows.
- **Drop** rows or columns from a DataFrame.
- **Modify** specific data points using selection.

In [39]:
# Setup for Demo
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [41]:
# [DEMO] Accessing a row by label using .loc
data.loc["Colorado"]

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

### 💡 Concept Demo: Loc vs Iloc
- **.loc[row_label, col_label]**: "Address" based.
- **.iloc[row_pos, col_pos]**: "GPS" based (integers).

In [42]:
# [DEMO] Select 'Colorado' row using loc
print("--- Row by Label ---")
display(data.loc["Colorado"])

# [DEMO] Select 'Colorado' row using iloc (it's at index 1)
print("\n--- Row by Position ---")
display(data.iloc[1])

--- Row by Label ---

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

--- Row by Position ---

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [43]:
# [DEMO] Boolean Filtering
# Select rows where column 'three' is greater than 5
data[data["three"] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### 📖 Concept: Dropping Rows and Columns
Use the `drop()` method to remove rows or columns. By default, it drops rows. Use `axis=1` or `axis="columns"` to drop columns.

In [ ]:
# [DEMO] Dropping rows and columns
print("Drop rows 'Colorado' and 'Ohio':")
display(data.drop(["Colorado", "Ohio"]))

print("\nDrop column 'two':")
display(data.drop("two", axis=1))

# These operations do not affect the original DataFrame unless we specify 'inplace=True:'

Drop rows 'Colorado' and 'Ohio':

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

Drop column 'two':

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

### 🛠️ Activity: Data Detective

**Tasks:**
Using the `data` DataFrame provided above:
1. Select the rows for 'Utah' and 'New York' only.
2. Select the value in the 'two' column for 'Ohio' (should be 1).
3. Select all rows where column 'three' is greater than 5.
4. Update the value of 'four' in the 'New York' row to be 100.

In [60]:
# [EXERCISE] Write your code here
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
print("Original DataFrame:")
display(data)
# 1. Utah and New York
print("Select rows for 'Utah' and 'New York':")
display(data.loc[["Utah", "New York"]])
# 2. 'two' for 'Ohio'
print("Select column 'two' for 'Ohio':")
display(data.loc["Ohio", "two"])
# 3. Filter all rows where column 'three' > 5
print("Filter rows where column 'three' > 5:")
display(data[data["three"] > 5])
# 4. Update value of column 'four' for 'New York' to 100
print("Update value of column 'four' for 'New York' to 100:")
data.loc["New York", "four"] = 100
display(data)

Original DataFrame:

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Select rows for 'Utah' and 'New York':

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

Select column 'two' for 'Ohio':

1

Filter rows where column 'three' > 5:

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Update value of column 'four' for 'New York' to 100:

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14   100

---

## 🎯 Section 3: Function Application, Sorting, & Ranking (60 min)

### Learning Objectives (LO3 & LO4)
By the end of this section, you will be able to:
- **Sort** data by index or values.
- **Rank** data to handle ties.
- **Apply** custom functions to transform data.

In [61]:
# Setup Data
frame = pd.DataFrame({
    "b": [4, 7, -3, 2], 
    "a": [0, 1, 0, 1]
}, index=['Row1', 'Row2', 'Row3', 'Row4'])
frame

      b  a
Row1  4  0
Row2  7  1
Row3 -3  0
Row4  2  1

### 💡 Concept Demo: Sorting & Ranking
1. `sort_index()`
2. `sort_values(by=...)`
3. `rank()`

In [63]:
# [DEMO] Sorting by index
sort_index = frame.sort_index()
display(sort_index)

      b  a
Row1  4  0
Row2  7  1
Row3 -3  0
Row4  2  1

In [64]:
# [DEMO] Sort by values in column 'b'
frame.sort_values(by="b")

      b  a
Row3 -3  0
Row4  2  1
Row1  4  0
Row2  7  1

In [65]:
# [DEMO] Sort by values in column 'b' in descending order
frame.sort_values(by="b", ascending=False)

      b  a
Row2  7  1
Row1  4  0
Row4  2  1
Row3 -3  0

In [84]:
print("Original Frame:")
display(frame)
# rank by column 'b' using 'min' method for ties and descending order
print("Ranked Frame:")
frame.rank(method='min', ascending=False)

Original Frame:

      b  a
Row1  4  0
Row2  7  1
Row3 -3  0
Row4  2  1

Ranked Frame:

        b    a
Row1  2.0  3.0
Row2  1.0  1.0
Row3  4.0  3.0
Row4  3.0  1.0

In [89]:
# [DEMO] Applying a function so that if value in column 'b' is greater than 2, label it as "Big", otherwise "Small"

def label_size(val):
    return "Big" if val > 2 else "Small"

frame['b_size'] = frame['b'].apply(label_size)
frame

      b  a b_size
Row1  4  0    Big
Row2  7  1    Big
Row3 -3  0  Small
Row4  2  1  Small

In [ ]:
# applying the same function on rows, use apply with axis=1 to apply the function to each row instead of each column

def label_size(row):
    if row['b'] > 2:
        return "Big"
    else:
        return "Small"
frame['b_size_row'] = frame.apply(label_size, axis=1)
frame

      b  a b_size b_size_row
Row1  4  0    Big        Big
Row2  7  1    Big        Big
Row3 -3  0  Small      Small
Row4  2  1  Small      Small

### 🛠️ Activity: Leaderboard Logic

**Scenario:** You have exam scores. You need to rank them and assign a Pass/Fail status.

**Tasks:**
1. Run the starter code to generate the `scores` DataFrame.
2. Sort the DataFrame by 'Math' score in descending order (highest first).
3. Create a new column 'Math_Rank' using the `.rank()` method.
4. Define a function that returns "Pass" if score >= 60 and "Fail" otherwise.
5. Apply this function to the 'Math' column to create a new 'Status' column.

In [ ]:
# [EXERCISE] Starter Code

scores = pd.DataFrame({
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Math": [85, 45, 92, 60],
    "Science": [70, 55, 88, 72]
})
print("Original Scores DataFrame:")
display(scores)

# Your code here

# 2. Sort the DataFrame by 'Math' score in descending order (highest first).
print("Sorted DataFrame by 'Math' score in descending order (highest first):")
sort_index = scores.sort_values(by="Math", ascending=False)
display(sort_index)

# 3. Create a new column 'Math_Rank' using the `.rank()` method in descending order so that the highest score gets rank 1, as integer ranks, where the new 'Math_Rank' column sorted by 'Math_Rank' in ascending order (rank 1 at the top).
print("DataFrame with 'Math_Rank' column:")
scores['Math_Rank'] = scores['Math'].rank(ascending=False).astype(int)
scores = scores.sort_values(by="Math_Rank")
display(scores)

# 4. Define a function that returns "Pass" if score >= 60 and "Fail" otherwise.
def evaluate_status(score):
    if score >= 60:
        return "Pass"
    else:
        return "Fail"

# 5. Apply this function to the 'Math' column to create a new 'pass or fail' column.
print("DataFrame with 'pass or fail' column:")
scores['Status'] = scores['Math'].apply(evaluate_status)
display(scores)

Original Scores DataFrame:

   Student  Math  Science
0    Alice    85       70
1      Bob    45       55
2  Charlie    92       88
3    David    60       72

Sorted DataFrame by 'Math' score in descending order (highest first):

   Student  Math  Science
2  Charlie    92       88
0    Alice    85       70
3    David    60       72
1      Bob    45       55

DataFrame with 'Math_Rank' column:

   Student  Math  Science  Math_Rank
2  Charlie    92       88          1
0    Alice    85       70          2
3    David    60       72          3
1      Bob    45       55          4

DataFrame with 'pass or fail' column:

   Student  Math  Science  Math_Rank Status
2  Charlie    92       88          1   Pass
0    Alice    85       70          2   Pass
3    David    60       72          3   Pass
1      Bob    45       55          4   Fail

## 🎓 Lesson Summary

1. **Data Structures:** Series (1D) and DataFrame (2D) are the building blocks.
2. **Missing Data:** Use `isna()` and `notna()` to detect missing values.
3. **Selection:** Use `.loc[]` for labels and `.iloc[]` for positions. Use `.drop()` to remove rows/columns.
4. **Operations:** Vectorized operations are faster than loops. Use `.apply()` for custom logic.
5. **Sorting:** Organize your data to find insights quickly.

**Next Steps:** In the next lesson, we will cover Data Cleaning (handling missing values) and Aggregation (GroupBy).